language: node_js

node_js:
  - "stable"

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: test
      script: npm run test
    # - stage: build
    #   script: npm run build
